name: NuGet Client

on:
  push:
    tags: "client-*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build --configuration Release
    - name: Package
      run: dotnet pack --configuration Release src/Balances.Client /p:Version=${GITHUB_REF#refs/tags/client-}
    - name: Publish
      run: dotnet nuget push src/Balances.Client/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}